import test from "node:test";
import assert from "node:assert/strict";
import { AudioEngine } from "../src/audio/audio-engine.js";
import { AudioEngineError } from "../src/audio/errors.js";
import type { AudioEngineEvent, BinauralSessionConfiguration } from "../src/audio/types.js";
import { MockAudioContextFactory, MockClock } from "./mocks/web-audio.mock.js";

function configuration(overrides: Partial<BinauralSessionConfiguration> = {}): BinauralSessionConfiguration {
  return { mode:"carrier-offset", carrierHz:200, binauralHz:6, masterVolume:0.08, leftVolume:0.5, rightVolume:0.5, durationSeconds:10, fadeInSeconds:1, fadeOutSeconds:0.3, transitionSeconds:0.08, ...overrides } as BinauralSessionConfiguration;
}
function setup(){const factory=new MockAudioContextFactory();const clock=new MockClock();const engine=new AudioEngine({contextFactory:factory,clock,progressIntervalMilliseconds:100});return{factory,clock,engine};}

test("não cria AudioContext no construtor",()=>{const{factory}=setup();assert.equal(factory.contexts.length,0);});
test("inicializa uma única instância de AudioContext",async()=>{const{factory,engine}=setup();await engine.initialize();await engine.initialize();assert.equal(factory.contexts.length,1);assert.equal(engine.getState().state,"idle");});
test("inicia com dois osciladores e separação por ChannelMerger",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();assert.equal(context.oscillators.length,2);assert.equal(context.mergers.length,1);assert.equal(context.mergers[0]?.inputs,2);assert.equal(context.gains[0]?.connections[0]?.input,0);assert.equal(context.gains[1]?.connections[0]?.input,1);assert.equal(engine.getState().state,"running");});
test("aplica fade-in obrigatório no master gain",async()=>{const{factory,engine}=setup();await engine.start(configuration());const masterGain=factory.latest().gains[2];assert.ok(masterGain);assert.ok(masterGain.gain.calls.some((call)=>call.method==="linear"&&call.value===0.08&&call.time===1));});
test("impede início duplicado",async()=>{const{engine}=setup();await engine.start(configuration());await assert.rejects(engine.start(configuration()),(error:unknown)=>error instanceof AudioEngineError&&error.code==="INVALID_STATE_TRANSITION");});
test("pausa e retoma usando suspend e resume",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();await engine.pause();assert.equal(engine.getState().state,"paused");assert.equal(engine.getState().pauseReason,"manual");assert.equal(context.suspendCalls,1);await engine.resume();assert.equal(engine.getState().state,"running");assert.equal(context.resumeCalls,2);});
test("pausa repetida é idempotente",async()=>{const{factory,engine}=setup();await engine.start(configuration());await engine.pause();await engine.pause();assert.equal(factory.latest().suspendCalls,1);});
test("rejeita pausa em idle",async()=>{const{engine}=setup();await engine.initialize();await assert.rejects(engine.pause(),(error:unknown)=>error instanceof AudioEngineError&&error.code==="INVALID_STATE_TRANSITION");});
test("parada aplica fade-out antes de encerrar os osciladores",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();const stopOperation=engine.stop();const left=context.oscillators[0],right=context.oscillators[1];assert.ok(left?.stoppedAt!==undefined&&left.stoppedAt>context.currentTime);assert.equal(left?.stoppedAt,right?.stoppedAt);context.advance(0.4);await stopOperation;assert.equal(engine.getState().state,"idle");assert.equal(engine.getState().graphActive,false);});
test("parada repetida aguarda a mesma limpeza",async()=>{const{factory,engine}=setup();await engine.start(configuration());const first=engine.stop(),second=engine.stop();factory.latest().advance(0.4);await Promise.all([first,second]);assert.equal(engine.getState().state,"idle");});
test("novo início cria novos osciladores após parada",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();const stopOperation=engine.stop();context.advance(0.4);await stopOperation;await engine.start(configuration());assert.equal(context.oscillators.length,4);});
test("alterações de frequência usam rampas sem recriar a cadeia",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();engine.setCarrierFrequency(210);engine.setBinauralFrequency(8);assert.equal(context.oscillators.length,2);assert.ok(context.oscillators[0]?.frequency.calls.some((call)=>call.method==="linear"&&call.value===210));assert.ok(context.oscillators[1]?.frequency.calls.some((call)=>call.method==="linear"&&call.value===218));});
test("altera volume de canal com rampa",async()=>{const{factory,engine}=setup();await engine.start(configuration());engine.setChannelVolume("left",0.25);const leftGain=factory.latest().gains[0];assert.ok(leftGain?.gain.calls.some((call)=>call.method==="linear"&&call.value===0.25));});
test("encerramento automático usa relógio do áudio",async()=>{const{factory,engine}=setup();const events:AudioEngineEvent[]=[];engine.subscribe((event)=>events.push(event));await engine.start(configuration({durationSeconds:2,fadeInSeconds:0.5,fadeOutSeconds:0.2}));factory.latest().advance(2);assert.equal(engine.getState().state,"idle");assert.ok(events.some((event)=>event.type==="autostop"));});
test("emite progresso desacoplado da UI",async()=>{const{factory,clock,engine}=setup();const events:AudioEngineEvent[]=[];engine.subscribe((event)=>events.push(event));await engine.start(configuration());factory.latest().advance(1.5);clock.tick(100);const progress=events.find((event)=>event.type==="progress");assert.ok(progress&&progress.type==="progress");assert.equal(progress.elapsedSeconds,1.5);});
test("suspensão externa é diferenciada de pausa manual",async()=>{const{factory,engine}=setup();await engine.start(configuration());factory.latest().externalSuspend();assert.equal(engine.getState().state,"interrupted");assert.equal(engine.getState().pauseReason,"external");});
test("recuperação externa não cria segunda cadeia",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();context.externalSuspend();await engine.recover(false);assert.equal(engine.getState().state,"running");assert.equal(context.oscillators.length,2);});
test("falha de resume retorna estado recuperável",async()=>{const{factory,engine}=setup();await engine.initialize();factory.latest().resumeFailure=new Error("blocked");await assert.rejects(engine.start(configuration()));assert.equal(engine.getState().state,"interaction-required");assert.equal(engine.getState().requiresUserGesture,true);});
test("contexto fechado externamente limpa nós e exige recuperação",async()=>{const{factory,engine}=setup();await engine.start(configuration());factory.latest().externalClose();assert.equal(engine.getState().state,"error");assert.equal(engine.getState().graphActive,false);assert.equal(engine.getState().requiresUserGesture,true);});
test("dispose fecha contexto e impede novo uso",async()=>{const{factory,engine}=setup();await engine.initialize();await engine.dispose();assert.equal(factory.latest().closeCalls,1);assert.equal(engine.getState().state,"disposed");await assert.rejects(engine.initialize(),(error:unknown)=>error instanceof AudioEngineError&&error.code==="ENGINE_DISPOSED");});
test("limpeza desconecta todos os nós",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();const stopOperation=engine.stop();context.advance(0.4);await stopOperation;assert.ok(context.oscillators.every((node)=>node.disconnected));assert.ok(context.gains.every((node)=>node.disconnected));assert.ok(context.mergers.every((node)=>node.disconnected));assert.ok(context.compressors.every((node)=>node.disconnected));});
test("parada enquanto pausado retoma apenas para processar o fade-out",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();await engine.pause();const operation=engine.stop();await Promise.resolve();assert.equal(context.resumeCalls,2);context.advance(0.4);await operation;assert.equal(engine.getState().state,"idle");});
test("volume alterado durante pausa é preservado na retomada",async()=>{const{engine}=setup();await engine.start(configuration());await engine.pause();engine.setMasterVolume(0.05);assert.equal(engine.getState().configuration?.masterVolume,0.05);await engine.resume();assert.equal(engine.getState().state,"running");});
test("retomada automática do contexto aplica recuperação sem recriar nós",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();context.externalSuspend();context.externalResume();assert.equal(engine.getState().state,"running");assert.equal(context.oscillators.length,2);});
test("contador corrige throttling visual usando currentTime do áudio",async()=>{const{factory,clock,engine}=setup();await engine.start(configuration({durationSeconds:20}));factory.latest().advance(7.25);clock.tick(5000);assert.equal(engine.getState().elapsedSeconds,7.25);assert.equal(engine.getState().remainingSeconds,12.75);});
test("falha de recuperação mantém interação requerida sem duplicação",async()=>{const{factory,engine}=setup();await engine.start(configuration());const context=factory.latest();context.externalSuspend();context.resumeFailure=new Error("blocked");await assert.rejects(engine.recover(false));assert.equal(engine.getState().state,"interaction-required");assert.equal(context.oscillators.length,2);});
