import test from "node:test";
import assert from "node:assert/strict";
import { AudioEngine } from "../src/audio/audio-engine.js";
import { BrowserLifecycleCoordinator } from "../src/lifecycle/browser-lifecycle.js";
import { PwaUpdateController } from "../src/lifecycle/pwa-update.js";
import { ScreenWakeLockController } from "../src/lifecycle/wake-lock.js";
import { MockAudioContextFactory, MockClock } from "./mocks/web-audio.mock.js";
import { MockServiceWorker, MockServiceWorkerContainer, MockWakeLockManager, MockWindow } from "./mocks/lifecycle.mock.js";

function setup(){const factory=new MockAudioContextFactory();const clock=new MockClock();const engine=new AudioEngine({contextFactory:factory,clock});const windowLike=new MockWindow();const lifecycle=new BrowserLifecycleCoordinator(engine,windowLike);return{factory,engine,windowLike,lifecycle};}
const session={mode:"carrier-offset" as const,carrierHz:200,binauralHz:6,durationSeconds:20,masterVolume:0.08,fadeInSeconds:0.5,fadeOutSeconds:0.2,transitionSeconds:0.08};

test("registro de listeners é idempotente e removido no dispose",async()=>{const{lifecycle,windowLike}=setup();lifecycle.attach();lifecycle.attach();assert.equal(windowLike.document.store.count("visibilitychange"),1);assert.equal(windowLike.store.count("pagehide"),1);await lifecycle.dispose();assert.equal(windowLike.document.store.count("visibilitychange"),0);assert.equal(windowLike.store.count("pagehide"),0);});
test("Wake Lock é adquirido durante sessão e liberado na pausa",async()=>{const{lifecycle,windowLike,engine}=setup();lifecycle.attach();await engine.start(session);await Promise.resolve();assert.equal(windowLike.wakeLock.requests,1);assert.equal(lifecycle.getState().wakeLock,"active");await engine.pause();await Promise.resolve();assert.equal(lifecycle.getState().wakeLock,"released");await lifecycle.dispose();});
test("Wake Lock não suportado não impede o funcionamento",async()=>{const statuses:string[]=[];const controller=new ScreenWakeLockController({onLine:true},(status)=>statuses.push(status));assert.equal(await controller.acquire(),"unsupported");assert.equal(await controller.release(),"unsupported");assert.ok(statuses.includes("unsupported"));});
test("falha de Wake Lock é tratada sem repetição infinita",async()=>{const manager=new MockWakeLockManager();manager.failure=new Error("denied");const controller=new ScreenWakeLockController({onLine:true,wakeLock:manager},()=>undefined);assert.equal(await controller.acquire(),"denied");assert.equal(manager.requests,1);});
test("retorno da visibilidade recupera suspensão externa sem duplicar osciladores",async()=>{const{lifecycle,windowLike,factory,engine}=setup();lifecycle.attach();await engine.start(session);const context=factory.latest();context.externalSuspend();assert.equal(engine.getState().state,"interrupted");windowLike.document.setVisibility("hidden");windowLike.document.setVisibility("visible");await Promise.resolve();await Promise.resolve();assert.equal(engine.getState().state,"running");assert.equal(context.oscillators.length,2);await lifecycle.dispose();});
test("pausa manual não é retomada automaticamente ao voltar à aba",async()=>{const{lifecycle,windowLike,engine}=setup();lifecycle.attach();await engine.start(session);await engine.pause();windowLike.document.setVisibility("hidden");windowLike.document.setVisibility("visible");await Promise.resolve();assert.equal(engine.getState().state,"paused");assert.equal(engine.getState().pauseReason,"manual");await lifecycle.dispose();});
test("pagehide persiste marcador e nova montagem informa interrupção",async()=>{const{lifecycle,windowLike,engine}=setup();lifecycle.attach();await engine.start(session);windowLike.emit("pagehide");assert.ok(windowLike.sessionStorage.length>0);await lifecycle.dispose();const secondEngine=new AudioEngine({contextFactory:new MockAudioContextFactory(),clock:new MockClock()});const secondLifecycle=new BrowserLifecycleCoordinator(secondEngine,windowLike);secondLifecycle.attach();assert.match(secondLifecycle.getState().recoveryMessage,/interrompida por recarregamento/u);assert.equal(secondEngine.getState().state,"uninitialized");await secondLifecycle.dispose();});
test("mudança de dispositivo gera orientação sem solicitar microfone",async()=>{const{lifecycle,windowLike}=setup();lifecycle.attach();windowLike.mediaDevices.emitDeviceChange();assert.match(lifecycle.getState().recoveryMessage,/Dispositivo de áudio alterado/u);await lifecycle.dispose();});
test("atualização da PWA é adiada durante sessão ativa",async()=>{const container=new MockServiceWorkerContainer();const waiting=new MockServiceWorker();waiting.state="installed";container.registration.waiting=waiting;let status="";const controller=new PwaUpdateController(container,()=>undefined,(value)=>{status=value;});await controller.register();controller.setSessionActive(true);controller.apply();assert.equal(status,"deferred");assert.equal(waiting.messages.length,0);controller.setSessionActive(false);controller.apply();assert.equal(status,"applying");assert.equal(waiting.messages.length,1);controller.dispose();});
test("atualização aplicada só recarrega após controllerchange e sem sessão",async()=>{const container=new MockServiceWorkerContainer();const waiting=new MockServiceWorker();waiting.state="installed";container.registration.waiting=waiting;let reloads=0;const controller=new PwaUpdateController(container,()=>{reloads+=1;},()=>undefined);await controller.register();controller.apply();assert.equal(reloads,0);container.emitControllerChange();assert.equal(reloads,1);controller.dispose();});
